#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PROG=/root/bos_heater_mqtt.py
ARGS=$(cat /root/bos_heater_args.txt)

start_service() {
        procd_open_instance
        procd_set_param command $PROG $ARGS
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}